all:
	g++ main.cpp MyFieldView.cpp EnemyFieldView.cpp ShotField.cpp GameConf.cpp Controller.cpp ConsoleGamer.cpp ConsoleView.cpp Field.cpp Game.cpp RandGamer.cpp OptGamer.cpp Ship.cpp -std=c++11 -g -Werror -o BattleShip.out
clean:
	rm -rf BattleShip.out
