all:
	g++ main.cpp Statistics.cpp View.cpp MyFieldView.cpp ShotPoint.cpp ShipPoint.cpp ShotParser.cpp myRand.cpp ShipParser.cpp GamerFactory.cpp Gamer.cpp ConsoleParser.cpp FieldView.cpp BaseParser.cpp EnemyFieldView.cpp ShotField.cpp GameConf.cpp Controller.cpp ConsoleGamer.cpp ConsoleView.cpp Field.cpp Game.cpp RandGamer.cpp OptGamer.cpp Ship.cpp -std=c++11 -g -Werror -o BattleShip.out
clean:
	rm -rf BattleShip.out
