all:
	g++ main.cpp MotionBlurFilter.cpp BlurMatrix.cpp EdgeFunctor.cpp EdgeMatrix.cpp Editor.cpp SharpMatrix.cpp CutFilter.cpp GrayscaleFunctor.cpp AgregateFilter.cpp FilterFactory.cpp BmpLoader.cpp BmpSaver.cpp Image.cpp NegativeFunctor.cpp Pixel.cpp ConsoleParser.cpp FilterDescription.cpp -O3 -std=c++11 -Wall -g -Werror -o cimg.out
clean:
	rm -rf cimg.out
