all:
	g++ main.cpp Editor.cpp AgregateFilter.cpp FilterFactory.cpp BmpLoader.cpp BmpSaver.cpp Image.cpp NegativeFunctor.cpp Pixel.cpp ConsoleParser.cpp FilterDescription.cpp -std=c++11 -g -Werror -o cimg.out
clean:
	rm -rf BattleShip.out
