all:
	g++ main.cpp LinkedListImpl.cpp LinkedList.cpp -std=c++11 -g -Werror -lgtest_main -lgtest -pthread -fprofile-arcs -ftest-coverage -o LinkedList_Test.out
clean:
	rm -rf LinkedList_Test.out
	rm -rf *.gcno
